server:
  port: 8002
spring:
  application:
    # 统一安全管理平台缩写 Unified Security Management Platform
    name: usmpService
  config:
    #spring cloud 202x版本后，禁用了bootstrap, 使用以下配置设置配置中心
    #详情查看https://docs.spring.io/spring-cloud-consul/reference/config.html
    import: optional:consul:localhost:8500
  cloud:
    consul:
      host: localhost
      port: 8500
      ####consul注册中心地址
      discovery:
        # 是否注册（默认为true）
        register: true
        # 服务名称
        service-name: ${spring.application.name}
        # 展示实例的ip（默认是false）
        prefer-ip-address: true
        # 实例id名称（默认是${spring.application.name}:comma,separated,profiles:${server.port}）
        instance-id: ${spring.application.name}
      config:
        # 是否启用配置中心,默认值 true 开启
        enabled: true
        # 设置配置的基本文件夹,默认值config 可以理解为配置文件所在的最外层文件夹
        prefixes: config
        # 设置应用的文件夹名称,默认值application 一般建议设置为微服务应用名称
        default-context: usmpService
        # 配置环境分隔符,默认值","和default-context配置项搭配
        # 例如应用usmpService 分别有环境 default, dev, test, prod
        # 只需 config 文件下创建 usmpService, usmpService-dev, usmpService-test, usmpService-prod文件夹
        profile-separator: '-'
        # 指定配置格式为yamL
        format: YAML
        # Consul Key/Values 中的Key, Value 对应整个配置文件
        data-key: usmpServiceConfig
        # 以上配置可以理解为:加载 config/usmpService/ 文件夹下Key 为usmpServiceConfig 的Value 对应的配置
        watch:
          # 是否开启自动刷新,默认值true 开启
          enabled: true
          # 刷新频率,单位:毫秒,默认值1000
          delay: 1000
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 1234.abcd
    url: jdbc:postgresql://localhost:5432/usmp
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    open-in-view: true